"""
Pipeline API Routes

This module exposes REST endpoints for:
1. Pipeline status / diagnostics
2. Pipeline lifecycle management
3. Pipeline configuration
4. Utility helpers
5. Live frame streaming
"""

# ============================================================================
# Imports
# ============================================================================

import json
import logging

import cv2
import numpy as np
from PIL import Image

from fastapi import APIRouter
from fastapi.responses import Response

from backend.api.schemas.pipeline import PipelineStartRequest
from backend.api.schemas.config import (
    FlowConfigRequest,
    DensityConfigRequest,
    SpeedConfigRequest,
)

from backend.config.model_config import MODEL_MAPS, CLASS_MAPS

from backend.core.pipeline_manager import CONFIG_PATH
from backend.core.state import manager

from backend.services.pipeline import VideoProcessingPipeline
from backend.services.video_source import VideoSource

logger = logging.getLogger(__name__)

# ============================================================================
# Router
# ============================================================================

router = APIRouter(prefix="/pipeline", tags=["pipeline"])


# ============================================================================
# Pipeline Status
# ============================================================================


@router.get("/statistics")
def pipeline_statistics():
    """
    Returns a complete snapshot of the current pipeline statistics.

    Response Fields:
    ---------------
    frame_index

    detections
        Number of objects detected in the latest processed frame.

    raw_detection_records
        Total number of detections recorded since the current
        pipeline session started.

    unique_vehicles
        Number of unique tracker IDs (vehicles/objects)
        observed during the current session.

    flow_statistics
        Statistics generated by the vehicle flow module.

        vehicle_distribution
            Total count of each vehicle class that has crossed
            configured counting lines.

        vehicle_scene
            Current number of each vehicle class visible
            in the frame.

        lane_distribution
            Lane-wise count of vehicles that have crossed
            each configured counting line.

        lane_scene
            Current vehicle count for each lane.

    density_statistics
        Statistics generated by the density estimation module.

        track_history
            Historical centroid positions for every tracked
            object. Used to generate density heatmaps.

        last_positions
            Most recent centroid position of each tracked object.

        heatmap_available
            Indicates whether a density heatmap has been
            initialized and is available.

        heatmap_shape
            Resolution of the generated density heatmap.

    speed_statistics
        Statistics generated by the speed estimation module.

        class_speed
            Average estimated speed grouped by vehicle class.

        time_speed
            Instantaneous speed history indexed over time
            or frame intervals.
    """
    stats = manager.get_statistics()
    return stats


@router.get("/status")
def pipeline_status():
    """
    Returns the current state of the backend pipeline.
    Used by the frontend to determine whether the
    processing pipeline is available.
    """
    return {"pipeline": "ready"}


@router.get("/current_config")
def get_current_config():
    """
    Returns the UI configuration that was most recently
    saved to disk, allowing settings to persist across
    pipeline restarts.
    """
    return manager.current_config


@router.get("/debug")
def pipeline_debug():
    """
    Reports whether a pipeline instance is currently loaded,
    along with which optional features (flow, density, speed)
    have been configured on it.
    """
    pipeline = manager.get_pipeline()

    if pipeline is None:
        return {"pipeline_loaded": False}

    return {
        "pipeline_loaded": True,
        "flow_enabled": len(pipeline.line_zones) > 0,
        "density_enabled": pipeline.density.heatmap is not None,
        "speed_enabled": pipeline.view_transformer is not None,
    }


@router.get("/debug/full")
def debug_full():
    """
    Returns low-level debug details about the active pipeline
    and its density heatmap, primarily for development use.
    """
    pipeline = manager.get_pipeline()

    if pipeline is None:
        return {"pipeline": None}

    return {
        "pipeline_id": id(pipeline),
        "density_id": id(pipeline.density),
        "heatmap_exists": pipeline.density.heatmap is not None,
        "heatmap_shape": (
            None if pipeline.density.heatmap is None else pipeline.density.heatmap.shape
        ),
    }


# ============================================================================
# Pipeline Lifecycle
# ============================================================================


@router.post("/start")
def start_pipeline(request: PipelineStartRequest):
    """
    Initializes and starts a complete video processing pipeline.

    Steps:
        1. Reset previous session
        2. Save UI configuration
        3. Convert selected class names into model class IDs
        4. Create the processing pipeline and video source
        5. Register runtime objects with the pipeline manager
        6. Start video capture and background processing
    """

    # ------------------------------------------------------------------
    # Reset any previous pipeline session.
    # ------------------------------------------------------------------
    manager.reset()

    # ------------------------------------------------------------------
    # Save current UI configuration to disk so it persists across restarts.
    # ------------------------------------------------------------------
    manager.current_config = {
        "camera_type": request.camera_type,
        "det_mode": request.det_mode,
        "confidence_threshold": request.confidence_threshold,
        "iou_threshold": request.iou_threshold,
        "frame_rate": request.frame_rate,
        "classes_to_detect": request.classes_to_detect,
    }

    try:
        with open(CONFIG_PATH, "w") as f:
            json.dump(manager.current_config, f, indent=5)
        logger.info(f"Config saved: {manager.current_config}")
    except Exception:
        logger.exception("Config save failed")

    # ------------------------------------------------------------------
    # Convert selected class names into model-specific class IDs.
    # ------------------------------------------------------------------
    model_map = MODEL_MAPS[request.camera_type]

    cls_map = {v: k for k, v in CLASS_MAPS[request.camera_type].items()}

    selected_class_ids = [
        CLASS_MAPS[request.camera_type][class_name]
        for class_name in request.classes_to_detect
        if class_name in CLASS_MAPS[request.camera_type]
    ]

    # ------------------------------------------------------------------
    # Create the processing pipeline and RTSP video source.
    # ------------------------------------------------------------------
    pipeline = VideoProcessingPipeline(
        det_mode=request.det_mode, model_map=model_map, frame_rate=request.frame_rate
    )

    video_source = VideoSource(source=request.rtsp_url, target_fps=request.frame_rate)

    # ------------------------------------------------------------------
    # Register all runtime objects with the global pipeline manager.
    # ------------------------------------------------------------------
    manager.set_pipeline(pipeline)
    manager.set_class_map(cls_map)
    manager.set_detection_thresholds(
        request.confidence_threshold, request.iou_threshold
    )
    manager.create_session(request.camera_type)
    manager.set_video_source(video_source)

    # ------------------------------------------------------------------
    # Start video capture and background processing.
    # ------------------------------------------------------------------
    video_source.start()
    manager.set_selected_classes(selected_class_ids)
    manager.start_processing()

    return {
        "status": "started",
        "camera_type": request.camera_type,
        "det_mode": request.det_mode,
    }


@router.post("/stop")
def stop_pipeline():
    """
    Stops the currently running pipeline session, releasing
    the video source and any associated processing resources.
    """
    if manager.video_source is not None:
        manager.video_source.stop()

    manager.stop_processing()
    manager.close_session()

    return {"status": "stopped"}


# ============================================================================
# Pipeline Configuration
# ============================================================================


@router.post("/config/flow")
def configure_flow(request: FlowConfigRequest):
    """
    Initializes virtual counting lines used for
    vehicle flow estimation.
    """
    pipeline = manager.get_pipeline()

    if pipeline is None:
        return {"error": "pipeline not loaded"}

    # Configure line zones used for vehicle counting.
    pipeline.initialize_flow_zones(request.line_params)

    return {"status": "flow configured", "lines": len(request.line_params)}


@router.post("/config/density")
def configure_density(request: DensityConfigRequest):
    """
    Initializes the density heatmap used for
    crowd/vehicle density estimation.
    """
    pipeline = manager.get_pipeline()

    if pipeline is None:
        return {"error": "pipeline not loaded"}
        # frame size
    pipeline.initialize_density((request.height, request.width, 3))

    return {
        "status": "density configured",
        "width": request.width,
        "height": request.height,
    }


@router.post("/config/speed")
def configure_speed(request: SpeedConfigRequest):
    """
    Initializes the perspective transform used to convert
    pixel coordinates into real-world distances for
    speed estimation.
    """
    pipeline = manager.get_pipeline()

    if pipeline is None:
        return {"error": "pipeline not loaded"}

    pipeline.initialize_speed_transform(
        source=np.array(request.source_points), target=np.array(request.target_points)
    )

    return {"status": "speed configured"}


# ============================================================================
# Utility Functions
# ============================================================================


def resize_frame_to_360p(frame):
    """
    Resizes an image while maintaining aspect ratio.

    Used for preview images to reduce bandwidth and
    improve frontend responsiveness.
    """
    image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

    # PIL preserves aspect ratio while resizing.
    image.thumbnail((640, 360))

    resized_frame = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

    return resized_frame


# ============================================================================
# Frame Streaming Endpoints
# ============================================================================


# used in the pipeline control tab in flow and speed estimation settings
@router.get("/preview_frame")
def preview_frame():
    """
    Captures a single frame directly from the RTSP camera
    feed for use as a lightweight preview image.
    """
    rtsp_url = "rtsp://arjun.badola:AB%23ai2025@10.0.102.54:554/"

    cap = cv2.VideoCapture(rtsp_url)

    success, frame = cap.read()
    cap.release()

    if not success:
        return {"error": "Unable to capture frame"}

    frame = resize_frame_to_360p(frame)
    # Convert NumPy array into JPEG bytes for HTTP response.
    _, buffer = cv2.imencode(".jpg", frame)

    return Response(content=buffer.tobytes(), media_type="image/jpeg")


# used in the analysis dashboard
@router.get("/live_frame")
def live_frame():
    """
    Returns the latest processed frame generated by
    the video processing pipeline.
    """
    frame = manager.latest_processed_frame

    if frame is None:
        return {"error": "No processed frame"}

    _, buffer = cv2.imencode(".jpg", frame)

    return Response(content=buffer.tobytes(), media_type="image/jpeg")


@router.get("/flow_frame")
def flow_frame():
    """
    Returns the latest annotated frame showing
    vehicle flow / counting line overlays.
    """
    frame = manager.latest_flow_frame

    if frame is None:
        return {"error": "No flow frame"}

    _, buffer = cv2.imencode(".jpg", frame)

    return Response(content=buffer.tobytes(), media_type="image/jpeg")


@router.get("/density_frame")
def density_frame():
    """
    Returns the latest density heatmap overlay.
    """
    frame = manager.latest_density_frame

    if frame is None:
        return {"error": "No density frame"}

    _, buffer = cv2.imencode(".jpg", frame)

    return Response(content=buffer.tobytes(), media_type="image/jpeg")
